doctrine_migrations:
    migrations_paths:
        'Surfnet\Migrations': '%kernel.project_dir%/src/Surfnet/Migrations'
    # namespace is arbitrary but should be different from App\Migrations
    # as migrations classes should NOT be autoloaded
    storage:
        table_storage:
            table_name: 'migration_versions'
            version_column_name: 'version'
            version_column_length: 192
