parameters:
    # All events should be registered here in order to be able to replay them
    registered_events:
        - Surfnet\Stepup\Configuration\Event\AllowedSecondFactorListUpdatedEvent
        - Surfnet\Stepup\Configuration\Event\ConfigurationUpdatedEvent
        - Surfnet\Stepup\Configuration\Event\EmailTemplatesUpdatedEvent
        - Surfnet\Stepup\Configuration\Event\IdentityProvidersUpdatedEvent
        - Surfnet\Stepup\Configuration\Event\InstitutionConfigurationRemovedEvent
        - Surfnet\Stepup\Configuration\Event\NewConfigurationCreatedEvent
        - Surfnet\Stepup\Configuration\Event\NewInstitutionConfigurationCreatedEvent
        - Surfnet\Stepup\Configuration\Event\RaLocationAddedEvent
        - Surfnet\Stepup\Configuration\Event\RaLocationContactInformationChangedEvent
        - Surfnet\Stepup\Configuration\Event\RaLocationRelocatedEvent
        - Surfnet\Stepup\Configuration\Event\RaLocationRemovedEvent
        - Surfnet\Stepup\Configuration\Event\RaLocationRenamedEvent
        - Surfnet\Stepup\Configuration\Event\ServiceProvidersUpdatedEvent
        - Surfnet\Stepup\Configuration\Event\ShowRaaContactInformationOptionChangedEvent
        - Surfnet\Stepup\Configuration\Event\SraaUpdatedEvent
        - Surfnet\Stepup\Configuration\Event\UseRaLocationsOptionChangedEvent
        - Surfnet\Stepup\Identity\Event\AppointedAsRaaEvent
        - Surfnet\Stepup\Identity\Event\AppointedAsRaEvent
        - Surfnet\Stepup\Identity\Event\CompliedWithUnverifiedSecondFactorRevocationEvent
        - Surfnet\Stepup\Identity\Event\IdentityAccreditedAsRaaEvent
        - Surfnet\Stepup\Identity\Event\IdentityEmailChangedEvent
        - Surfnet\Stepup\Identity\Event\GssfPossessionProvenEvent
        - Surfnet\Stepup\Identity\Event\IdentityAccreditedAsRaEvent
        - Surfnet\Stepup\Identity\Event\IdentityCreatedEvent
        - Surfnet\Stepup\Identity\Event\EmailVerifiedEvent
        - Surfnet\Stepup\Identity\Event\CompliedWithVettedSecondFactorRevocationEvent
        - Surfnet\Stepup\Identity\Event\CompliedWithVerifiedSecondFactorRevocationEvent
        - Surfnet\Stepup\Identity\Event\IdentityForgottenEvent
        - Surfnet\Stepup\Identity\Event\IdentityRenamedEvent
        - Surfnet\Stepup\Identity\Event\LocalePreferenceExpressedEvent
        - Surfnet\Stepup\Identity\Event\InstitutionsAddedToWhitelistEvent
        - Surfnet\Stepup\Identity\Event\PhonePossessionProvenEvent
        - Surfnet\Stepup\Identity\Event\RegistrationAuthorityRetractedEvent
        - Surfnet\Stepup\Identity\Event\RegistrationAuthorityInformationAmendedEvent
        - Surfnet\Stepup\Identity\Event\InstitutionsRemovedFromWhitelistEvent
        - Surfnet\Stepup\Identity\Event\SecondFactorVettedEvent
        - Surfnet\Stepup\Identity\Event\SecondFactorVettedWithoutTokenProofOfPossession
        - Surfnet\Stepup\Identity\Event\VerifiedSecondFactorRevokedEvent
        - Surfnet\Stepup\Identity\Event\WhitelistCreatedEvent
        - Surfnet\Stepup\Identity\Event\UnverifiedSecondFactorRevokedEvent
        - Surfnet\Stepup\Identity\Event\VettedSecondFactorRevokedEvent
        - Surfnet\Stepup\Identity\Event\WhitelistReplacedEvent
        - Surfnet\Stepup\Identity\Event\YubikeySecondFactorBootstrappedEvent
        - Surfnet\Stepup\Identity\Event\YubikeyPossessionProvenEvent
        # New versions for the IdentityAccreditedAsRaEvent and IdentityAccreditedAsRaaEvent events
        - Surfnet\Stepup\Identity\Event\IdentityAccreditedAsRaForInstitutionEvent
        - Surfnet\Stepup\Identity\Event\IdentityAccreditedAsRaaForInstitutionEvent
        # New versions for the AppointedAsRaEvent and AppointedAsRaa events
        - Surfnet\Stepup\Identity\Event\AppointedAsRaForInstitutionEvent
        - Surfnet\Stepup\Identity\Event\AppointedAsRaaForInstitutionEvent
        # New versions for the RegistrationAuthorityInformationAmendedEvent
        - Surfnet\Stepup\Identity\Event\RegistrationAuthorityInformationAmendedForInstitutionEvent
        # New versions for the RegistrationAuthorityRetractedEvent event
        - Surfnet\Stepup\Identity\Event\RegistrationAuthorityRetractedForInstitutionEvent
