framework:
    mailer:
        dsn: "%mailer_transport%://%mailer_user%:%mailer_password%@%mailer_host%:%mailer_port%"

when@test:
    framework:
        mailer:
            dsn: 'null://null' # disable delivery
