services:
  twig.extension.stringloader:
    class: Twig_Extension_StringLoader
    tags: [{ name: twig.extension }]
  twig.extension.sandbox:
    class: Twig_Extension_Sandbox
    arguments: [ "@twig.extension.sandbox.policy" ]
    tags: [{ name: twig.extension }]
  twig.extension.sandbox.policy:
    class: Twig_Sandbox_SecurityPolicy
    arguments:
      - [ if, else, elseif, for ] # Allowed tags
      - [ escape, localizeddate ] # Allowed filters
      - # Allowed methods
        Surfnet\Stepup\Identity\Value\CommonName:
          - __toString
        Surfnet\Stepup\Configuration\Value\ContactInformation:
          - __toString
        Surfnet\Stepup\Configuration\Value\Location:
          - __toString
        Surfnet\Stepup\Configuration\Value\RaLocationName:
          - __toString
        Surfnet\Stepup\DateTime\DateTime:
          - __toString
        Surfnet\StepupMiddleware\ApiBundle\Identity\Value\RegistrationAuthorityCredentials:
          - getCommonName
          - getLocation
          - getContactInformation
        Surfnet\Stepup\Identity\Value\Location:
          - __toString
        Surfnet\Stepup\Identity\Value\ContactInformation:
          - __toString
      - # Allowed properties
        Surfnet\StepupMiddleware\ApiBundle\Configuration\Entity\RaLocation:
          - name
          - location
          - contactInformation
      - [] # Allowed functions