services:
    surfnet_stepup_middleware_api.projector.identity:
        class: Surfnet\StepupMiddleware\ApiBundle\Identity\Projector\IdentityProjector
        arguments:
            - @surfnet_stepup_middleware_api.repository.identity
        tags: [{ name: event_bus.event_listener }]

    surfnet_stepup_middleware_api.projector.institution_listing:
        class: Surfnet\StepupMiddleware\ApiBundle\Identity\Projector\InstitutionListingProjector
        arguments:
            - @surfnet_stepup_middleware_api.repository.institution_listing
        tags: [{ name: event_bus.event_listener }]

    surfnet_stepup_middleware_api.projector.second_factor:
        class: Surfnet\StepupMiddleware\ApiBundle\Identity\Projector\SecondFactorProjector
        arguments:
            - @surfnet_stepup_middleware_api.repository.unverified_second_factor
            - @surfnet_stepup_middleware_api.repository.verified_second_factor
            - @surfnet_stepup_middleware_api.repository.vetted_second_factor
            - @surfnet_stepup_middleware_api.repository.identity
        tags: [{ name: event_bus.event_listener }]

    surfnet_stepup_middleware_api.projector.ra_second_factor:
        class: Surfnet\StepupMiddleware\ApiBundle\Identity\Projector\RaSecondFactorProjector
        arguments:
            - @surfnet_stepup_middleware_api.repository.ra_second_factor
            - @surfnet_stepup_middleware_api.repository.identity
        tags: [{ name: event_bus.event_listener }]

    surfnet_stepup_middleware_api.projector.ra_listing:
        class: Surfnet\StepupMiddleware\ApiBundle\Identity\Projector\RaListingProjector
        arguments:
            - @surfnet_stepup_middleware_api.repository.ra_listing
            - @surfnet_stepup_middleware_api.repository.identity
        tags: [{ name: event_bus.event_listener }]

    surfnet_stepup_middleware_api.projector.ra_candidate:
        class: Surfnet\StepupMiddleware\ApiBundle\Identity\Projector\RaCandidateProjector
        arguments:
            - @surfnet_stepup_middleware_api.repository.ra_candidate
        tags: [{ name: event_bus.event_listener }]

    surfnet_stepup_middleware_api.projector.sraa:
        class: Surfnet\StepupMiddleware\ApiBundle\Identity\Projector\SraaProjector
        arguments:
            - @surfnet_stepup_middleware_api.repository.sraa
        tags: [{ name: event_bus.event_listener }]

    surfnet_stepup_middleware_api.projector.audit_log:
        class: Surfnet\StepupMiddleware\ApiBundle\Identity\Projector\AuditLogProjector
        arguments:
            - @surfnet_stepup_middleware_api.repository.audit_log
            - @surfnet_stepup_middleware_api.repository.identity
        tags: [{ name: event_bus.event_listener }]

    surfnet_stepup_middleware_api.projector.second_factor_revocation:
        class: Surfnet\StepupMiddleware\ApiBundle\Identity\Projector\SecondFactorRevocationProjector
        arguments:
            - @surfnet_stepup_middleware_api.repository.second_factor_revocation
        tags: [{ name: event_bus.event_listener }]

    surfnet_stepup_middleware_api.projector.whitelist_entry:
        class: Surfnet\StepupMiddleware\ApiBundle\Identity\Projector\WhitelistProjector
        arguments:
            - @surfnet_stepup_middleware_api.repository.whitelist_entry
        tags: [{ name: event_bus.event_listener }]
