services:
    surfnet_stepup_middleware_api.projector.identity:
        class: Surfnet\StepupMiddleware\ApiBundle\Identity\Projector\IdentityProjector
        arguments: [ @surfnet_stepup_middleware_api.repository.identity ]
        tags: [{ name: event_bus.event_listener }]

    surfnet_stepup_middleware_api.projector.second_factor:
        class: Surfnet\StepupMiddleware\ApiBundle\Identity\Projector\SecondFactorProjector
        arguments:
            - @surfnet_stepup_middleware_api.repository.unverified_second_factor
            - @surfnet_stepup_middleware_api.repository.verified_second_factor
            - @surfnet_stepup_middleware_api.repository.vetted_second_factor
            - @surfnet_stepup_middleware_api.repository.identity
        tags: [{ name: event_bus.event_listener }]

    surfnet_stepup_middleware_api.projector.raa:
        class: Surfnet\StepupMiddleware\ApiBundle\Identity\Projector\RaaProjector
        arguments:
            - @surfnet_stepup_middleware_api.repository.raa
        tags: [{ name: event_bus.event_listener }]

    surfnet_stepup_middleware_api.projector.sraa:
        class: Surfnet\StepupMiddleware\ApiBundle\Identity\Projector\SraaProjector
        arguments:
            - @surfnet_stepup_middleware_api.repository.sraa
        tags: [{ name: event_bus.event_listener }]
