command_handle:
    path: /command
    defaults:  { _controller: SurfnetStepupMiddlewareApiBundle:Command:handle }
    methods:   [POST]
    condition: "request.headers.get('Content-Type') == 'application/json' && request.headers.get('Accept') matches '/^application\\\\/json($|[;,])/'"

identity:
    path:     /identity/{id}
    defaults: { _controller: SurfnetStepupMiddlewareApiBundle:Identity:get }
    methods:  [GET]
    condition: "request.headers.get('Accept') matches '/^application\\\\/json($|[;,])/'"

identity_second_factors:
    path:     /identity/{identityId}/second-factors
    defaults: { _controller: SurfnetStepupMiddlewareApiBundle:SecondFactor:findByIdentity }
    methods:  [GET]
    condition: "request.headers.get('Accept') matches '/^application\\\\/json($|[;,])/'"

identity_unverified_second_factors:
    path:     /identity/{identityId}/unverified-second-factors
    defaults: { _controller: SurfnetStepupMiddlewareApiBundle:SecondFactor:findUnverifiedByIdentity }
    methods:  [GET]
    condition: "request.headers.get('Accept') matches '/^application\\\\/json($|[;,])/'"
