services:
    surfnet_stepup_middleware_api.request.command_param_converter:
        class: Surfnet\StepupMiddleware\ApiBundle\Request\CommandParamConverter
        tags:
            - { name: request.param_converter, priority: -1, converter: surfnet_stepup_middleware_api.command }

    surfnet_stepup_middleware_api.listener.bad_command_request_exception_listener:
        class: Surfnet\StepupMiddleware\ApiBundle\EventListener\BadCommandRequestExceptionListener
        tags:
            - { name: kernel.event_listener, event: kernel.exception, method: onKernelException }

    surfnet_stepup_middleware_api.security.json_basic_auth_entry_point:
        class: Surfnet\StepupMiddleware\ApiBundle\Security\Http\EntryPoint\JsonBasicAuthenticationEntryPoint
        arguments:
            - ~ # HTTP Basic realm string, see extension

    surfnet_stepup_middleware_api.repository.identity:
        class: Surfnet\StepupMiddleware\ApiBundle\Identity\Repository\IdentityRepository
        factory_service: doctrine.orm.middleware_entity_manager
        factory_method: getRepository
        arguments: [ Surfnet\StepupMiddleware\ApiBundle\Identity\Entity\Identity ]

    surfnet_stepup_middleware_api.service.identity:
        class: Surfnet\StepupMiddleware\ApiBundle\Identity\Service\IdentityService
        arguments: [ @surfnet_stepup_middleware_api.repository.identity ]

    surfnet_stepup_middleware_api.repository.second_factor:
        class: Surfnet\StepupMiddleware\ApiBundle\Identity\Repository\SecondFactorRepository
        factory_service: doctrine.orm.middleware_entity_manager
        factory_method: getRepository
        arguments: [ Surfnet\StepupMiddleware\ApiBundle\Identity\Entity\SecondFactor ]

    surfnet_stepup_middleware_api.service.second_factor:
        class: Surfnet\StepupMiddleware\ApiBundle\Identity\Service\SecondFactorService
        arguments: [ @surfnet_stepup_middleware_api.repository.second_factor ]
