services:
    # Domain
    surfnet_stepup_middleware_api.repository.identity:
        class: Surfnet\StepupMiddleware\ApiBundle\Identity\Repository\IdentityRepository
        factory_service: doctrine.orm.middleware_entity_manager
        factory_method: getRepository
        arguments: [ Surfnet\StepupMiddleware\ApiBundle\Identity\Entity\Identity ]

    surfnet_stepup_middleware_api.repository.raa:
        class: Surfnet\StepupMiddleware\ApiBundle\Identity\Repository\RaaRepository
        factory_service: doctrine.orm.middleware_entity_manager
        factory_method: getRepository
        arguments: [ Surfnet\StepupMiddleware\ApiBundle\Identity\Entity\Raa ]

    surfnet_stepup_middleware_api.service.identity:
        class: Surfnet\StepupMiddleware\ApiBundle\Identity\Service\IdentityService
        arguments: [ @surfnet_stepup_middleware_api.repository.identity ]

    # Param Converters
    surfnet_stepup_middleware_api.request.command_param_converter:
        class: Surfnet\StepupMiddleware\ApiBundle\Request\CommandParamConverter
        tags:
            - { name: request.param_converter, priority: -10, converter: surfnet_stepup_middleware_api.command }

    surfnet_stepup_middleware_api.request.institution_param_converter:
        class: Surfnet\StepupMiddleware\ApiBundle\Request\InstitutionParamConverter
        tags:
            - { name: request.param_converter, priority: -5, converter: surfnet_step_middleware.institution }

    # Exception Listeners
    surfnet_stepup_middleware_api.listener.bad_command_request_exception_listener:
        class: Surfnet\StepupMiddleware\ApiBundle\EventListener\BadCommandRequestExceptionListener
        tags:
            - { name: kernel.event_listener, event: kernel.exception, method: onKernelException }

    surfnet_stepup_middleware_api.listener.bad_api_request_exception_listener:
            class: Surfnet\StepupMiddleware\ApiBundle\EventListener\BadApiRequestExceptionListener
            tags:
                - { name: kernel.event_listener, event: kernel.exception, method: onKernelException }

    # Security Entry Point
    surfnet_stepup_middleware_api.security.json_basic_auth_entry_point:
        class: Surfnet\StepupMiddleware\ApiBundle\Security\Http\EntryPoint\JsonBasicAuthenticationEntryPoint
        arguments:
            - ~ # HTTP Basic realm string, see extension

    surfnet_stepup_middleware_api.repository.identity:
        class: Surfnet\StepupMiddleware\ApiBundle\Identity\Repository\IdentityRepository
        factory_service: doctrine.orm.middleware_entity_manager
        factory_method: getRepository
        arguments: [ Surfnet\StepupMiddleware\ApiBundle\Identity\Entity\Identity ]

    surfnet_stepup_middleware_api.service.identity:
        class: Surfnet\StepupMiddleware\ApiBundle\Identity\Service\IdentityService
        arguments: [ @surfnet_stepup_middleware_api.repository.identity ]

    surfnet_stepup_middleware_api.repository.unverified_second_factor:
        class: Surfnet\StepupMiddleware\ApiBundle\Identity\Repository\UnverifiedSecondFactorRepository
        factory_service: doctrine.orm.middleware_entity_manager
        factory_method: getRepository
        arguments: [ Surfnet\StepupMiddleware\ApiBundle\Identity\Entity\UnverifiedSecondFactor ]

    surfnet_stepup_middleware_api.repository.verified_second_factor:
        class: Surfnet\StepupMiddleware\ApiBundle\Identity\Repository\VerifiedSecondFactorRepository
        factory_service: doctrine.orm.middleware_entity_manager
        factory_method: getRepository
        arguments: [ Surfnet\StepupMiddleware\ApiBundle\Identity\Entity\VerifiedSecondFactor ]

    surfnet_stepup_middleware_api.service.second_factor:
        class: Surfnet\StepupMiddleware\ApiBundle\Identity\Service\SecondFactorService
        arguments:
            - @surfnet_stepup_middleware_api.repository.unverified_second_factor
            - @surfnet_stepup_middleware_api.repository.verified_second_factor
