services:
    # Repositories
    surfnet_stepup_middleware_api.repository.identity:
        class: Surfnet\StepupMiddleware\ApiBundle\Identity\Repository\IdentityRepository
        factory_service: doctrine.orm.middleware_entity_manager
        factory_method: getRepository
        arguments: [ Surfnet\StepupMiddleware\ApiBundle\Identity\Entity\Identity ]

    surfnet_stepup_middleware_api.repository.ra:
        class: Surfnet\StepupMiddleware\ApiBundle\Identity\Repository\RaRepository
        factory_service: doctrine.orm.middleware_entity_manager
        factory_method: getRepository
        arguments: [ Surfnet\StepupMiddleware\ApiBundle\Identity\Entity\Ra ]

    surfnet_stepup_middleware_api.repository.raa:
        class: Surfnet\StepupMiddleware\ApiBundle\Identity\Repository\RaaRepository
        factory_service: doctrine.orm.middleware_entity_manager
        factory_method: getRepository
        arguments: [ Surfnet\StepupMiddleware\ApiBundle\Identity\Entity\Raa ]

    surfnet_stepup_middleware_api.repository.sraa:
        class: Surfnet\StepupMiddleware\ApiBundle\Identity\Repository\SraaRepository
        factory_service: doctrine.orm.middleware_entity_manager
        factory_method: getRepository
        arguments: [ Surfnet\StepupMiddleware\ApiBundle\Identity\Entity\Sraa ]

    surfnet_stepup_middleware_api.repository.unverified_second_factor:
        class: Surfnet\StepupMiddleware\ApiBundle\Identity\Repository\UnverifiedSecondFactorRepository
        factory_service: doctrine.orm.middleware_entity_manager
        factory_method: getRepository
        arguments: [ Surfnet\StepupMiddleware\ApiBundle\Identity\Entity\UnverifiedSecondFactor ]

    surfnet_stepup_middleware_api.repository.verified_second_factor:
        class: Surfnet\StepupMiddleware\ApiBundle\Identity\Repository\VerifiedSecondFactorRepository
        factory_service: doctrine.orm.middleware_entity_manager
        factory_method: getRepository
        arguments: [ Surfnet\StepupMiddleware\ApiBundle\Identity\Entity\VerifiedSecondFactor ]

    surfnet_stepup_middleware_api.repository.vetted_second_factor:
        class: Surfnet\StepupMiddleware\ApiBundle\Identity\Repository\VettedSecondFactorRepository
        factory_service: doctrine.orm.middleware_entity_manager
        factory_method: getRepository
        arguments: [ Surfnet\StepupMiddleware\ApiBundle\Identity\Entity\VettedSecondFactor ]

    surfnet_stepup_middleware_api.repository.ra_second_factor:
        class: Surfnet\StepupMiddleware\ApiBundle\Identity\Repository\RaSecondFactorRepository
        factory_service: doctrine.orm.middleware_entity_manager
        factory_method: getRepository
        arguments: [ Surfnet\StepupMiddleware\ApiBundle\Identity\Entity\RaSecondFactor ]

    surfnet_stepup_middleware_api.repository.audit_log:
        class: Surfnet\StepupMiddleware\ApiBundle\Identity\Repository\AuditLogRepository
        factory_service: doctrine.orm.middleware_entity_manager
        factory_method: getRepository
        arguments: [ Surfnet\StepupMiddleware\ApiBundle\Identity\Entity\AuditLogEntry ]

    # Domain Services
    surfnet_stepup_middleware_api.service.abstract_search:
        class: Surfnet\StepupMiddleware\ApiBundle\Identity\Service\AbstractSearchService
        abstract: true

    surfnet_stepup_middleware_api.service.second_factor:
        class: Surfnet\StepupMiddleware\ApiBundle\Identity\Service\SecondFactorService
        parent: surfnet_stepup_middleware_api.service.abstract_search
        arguments:
            - @surfnet_stepup_middleware_api.repository.unverified_second_factor
            - @surfnet_stepup_middleware_api.repository.verified_second_factor
            - @surfnet_stepup_middleware_api.repository.vetted_second_factor

    surfnet_stepup_middleware_api.service.ra_second_factor:
        class: Surfnet\StepupMiddleware\ApiBundle\Identity\Service\RaSecondFactorService
        parent: surfnet_stepup_middleware_api.service.abstract_search
        arguments:
            - @surfnet_stepup_middleware_api.repository.ra_second_factor

    surfnet_stepup_middleware_api.service.identity:
        class: Surfnet\StepupMiddleware\ApiBundle\Identity\Service\IdentityService
        parent: surfnet_stepup_middleware_api.service.abstract_search
        arguments:
            - @surfnet_stepup_middleware_api.repository.identity
            - @surfnet_stepup_middleware_api.repository.ra
            - @surfnet_stepup_middleware_api.repository.raa
            - @surfnet_stepup_middleware_api.repository.sraa

    surfnet_stepup_middleware_api.service.ra:
        class: Surfnet\StepupMiddleware\ApiBundle\Identity\Service\RaService
        parent: surfnet_stepup_middleware_api.service.abstract_search
        arguments:
            - @surfnet_stepup_middleware_api.repository.ra
            - @surfnet_stepup_middleware_api.repository.raa
            - @surfnet_stepup_middleware_api.repository.identity

    surfnet_stepup_middleware_api.service.raa:
        class: Surfnet\StepupMiddleware\ApiBundle\Identity\Service\RaaService
        parent: surfnet_stepup_middleware_api.service.abstract_search
        arguments:
            - @surfnet_stepup_middleware_api.repository.raa

    surfnet_stepup_middleware_api.service.sraa:
        class: Surfnet\StepupMiddleware\ApiBundle\Identity\Service\SraaService
        parent: surfnet_stepup_middleware_api.service.abstract_search
        arguments:
            - @surfnet_stepup_middleware_api.repository.sraa

    # Param Converters
    surfnet_stepup_middleware_api.request.command_param_converter:
        class: Surfnet\StepupMiddleware\ApiBundle\Request\CommandParamConverter
        tags:
            - { name: request.param_converter, priority: -10, converter: surfnet_stepup_middleware_api.command }

    surfnet_stepup_middleware_api.request.metadata_param_converter:
        class: Surfnet\StepupMiddleware\ApiBundle\Request\MetadataParamConverter
        arguments:
            - @validator
        tags:
            - { name: request.param_converter, priority: -15, converter: surfnet_stepup_middleware_api.metadata }

    surfnet_stepup_middleware_api.request.institution_param_converter:
        class: Surfnet\StepupMiddleware\ApiBundle\Request\InstitutionParamConverter
        tags:
            - { name: request.param_converter, priority: -5, converter: surfnet_step_middleware.institution }

    # Exception Listeners
    surfnet_stepup_middleware_api.listener.exception_listener:
            class: Surfnet\StepupMiddleware\ApiBundle\EventListener\ExceptionListener
            arguments:
                - @logger
            tags:
                - { name: kernel.event_listener, event: kernel.exception, method: onKernelException }

    # Security Entry Point
    surfnet_stepup_middleware_api.security.json_basic_auth_entry_point:
        class: Surfnet\StepupMiddleware\ApiBundle\Security\Http\EntryPoint\JsonBasicAuthenticationEntryPoint
        arguments:
            - ~ # HTTP Basic realm string, see extension
