services:
    # Repositories
    surfnet_stepup_middleware_api.repository.configured_institution:
        class: Surfnet\StepupMiddleware\ApiBundle\Configuration\Repository\ConfiguredInstitutionRepository
        factory: ["@doctrine.orm.middleware_entity_manager", getRepository]
        arguments: [ Surfnet\StepupMiddleware\ApiBundle\Configuration\Entity\ConfiguredInstitution ]

    surfnet_stepup_middleware_api.repository.institution_configuration_options:
        class: Surfnet\StepupMiddleware\ApiBundle\Configuration\Repository\InstitutionConfigurationOptionsRepository
        factory: ["@doctrine.orm.middleware_entity_manager", getRepository]
        arguments: [ Surfnet\StepupMiddleware\ApiBundle\Configuration\Entity\InstitutionConfigurationOptions ]

    surfnet_stepup_middleware_api.repository.ra_location:
        class: Surfnet\StepupMiddleware\ApiBundle\Configuration\Repository\RaLocationRepository
        factory: ["@doctrine.orm.middleware_entity_manager", getRepository]
        arguments: [ Surfnet\StepupMiddleware\ApiBundle\Configuration\Entity\RaLocation ]

    surfnet_stepup_middleware_api.repository.identity:
        class: Surfnet\StepupMiddleware\ApiBundle\Identity\Repository\IdentityRepository
        factory: ["@doctrine.orm.middleware_entity_manager", getRepository]
        arguments: [ Surfnet\StepupMiddleware\ApiBundle\Identity\Entity\Identity ]

    surfnet_stepup_middleware_api.repository.institution_listing:
        class: Surfnet\StepupMiddleware\ApiBundle\Identity\Repository\InstitutionListingRepository
        factory: ["@doctrine.orm.middleware_entity_manager", getRepository]
        arguments: [ Surfnet\StepupMiddleware\ApiBundle\Identity\Entity\InstitutionListing ]

    surfnet_stepup_middleware_api.repository.ra_candidate:
        class: Surfnet\StepupMiddleware\ApiBundle\Identity\Repository\RaCandidateRepository
        factory: ["@doctrine.orm.middleware_entity_manager", getRepository]
        arguments: [ Surfnet\StepupMiddleware\ApiBundle\Identity\Entity\RaCandidate ]

    surfnet_stepup_middleware_api.repository.ra_listing:
        class: Surfnet\StepupMiddleware\ApiBundle\Identity\Repository\RaListingRepository
        factory: ["@doctrine.orm.middleware_entity_manager", getRepository]
        arguments: [ Surfnet\StepupMiddleware\ApiBundle\Identity\Entity\RaListing ]

    surfnet_stepup_middleware_api.repository.sraa:
        class: Surfnet\StepupMiddleware\ApiBundle\Identity\Repository\SraaRepository
        factory: ["@doctrine.orm.middleware_entity_manager", getRepository]
        arguments: [ Surfnet\StepupMiddleware\ApiBundle\Identity\Entity\Sraa ]

    surfnet_stepup_middleware_api.repository.unverified_second_factor:
        class: Surfnet\StepupMiddleware\ApiBundle\Identity\Repository\UnverifiedSecondFactorRepository
        factory: ["@doctrine.orm.middleware_entity_manager", getRepository]
        arguments: [ Surfnet\StepupMiddleware\ApiBundle\Identity\Entity\UnverifiedSecondFactor ]

    surfnet_stepup_middleware_api.repository.verified_second_factor:
        class: Surfnet\StepupMiddleware\ApiBundle\Identity\Repository\VerifiedSecondFactorRepository
        factory: ["@doctrine.orm.middleware_entity_manager", getRepository]
        arguments: [ Surfnet\StepupMiddleware\ApiBundle\Identity\Entity\VerifiedSecondFactor ]

    surfnet_stepup_middleware_api.repository.vetted_second_factor:
        class: Surfnet\StepupMiddleware\ApiBundle\Identity\Repository\VettedSecondFactorRepository
        factory: ["@doctrine.orm.middleware_entity_manager", getRepository]
        arguments: [ Surfnet\StepupMiddleware\ApiBundle\Identity\Entity\VettedSecondFactor ]

    surfnet_stepup_middleware_api.repository.ra_second_factor:
        class: Surfnet\StepupMiddleware\ApiBundle\Identity\Repository\RaSecondFactorRepository
        factory: ["@doctrine.orm.middleware_entity_manager", getRepository]
        arguments: [ Surfnet\StepupMiddleware\ApiBundle\Identity\Entity\RaSecondFactor ]

    surfnet_stepup_middleware_api.repository.audit_log:
        class: Surfnet\StepupMiddleware\ApiBundle\Identity\Repository\AuditLogRepository
        factory: ["@doctrine.orm.middleware_entity_manager", getRepository]
        arguments: [ Surfnet\StepupMiddleware\ApiBundle\Identity\Entity\AuditLogEntry ]

    surfnet_stepup_middleware_api.repository.second_factor_revocation:
        class: Surfnet\StepupMiddleware\ApiBundle\Identity\Repository\SecondFactorRevocationRepository
        factory: ["@doctrine.orm.middleware_entity_manager", getRepository]
        arguments: [ Surfnet\StepupMiddleware\ApiBundle\Identity\Entity\SecondFactorRevocation]

    surfnet_stepup_middleware_api.repository.whitelist_entry:
        class: Surfnet\StepupMiddleware\ApiBundle\Identity\Repository\WhitelistEntryRepository
        factory: ["@doctrine.orm.middleware_entity_manager", getRepository]
        arguments: [ Surfnet\StepupMiddleware\ApiBundle\Identity\Entity\WhitelistEntry ]

    # Domain Services
    surfnet_stepup_middleware_api.service.institution_configuration_options:
        class: Surfnet\StepupMiddleware\ApiBundle\Service\InstitutionConfigurationOptionsService
        arguments:
            - "@surfnet_stepup_middleware_api.repository.institution_configuration_options"

    surfnet_stepup_middleware_api.service.configured_institutions:
        class: Surfnet\StepupMiddleware\ApiBundle\Configuration\Service\ConfiguredInstitutionService
        arguments:
            - "@surfnet_stepup_middleware_api.repository.configured_institution"

    surfnet_stepup_middleware_api.service.ra_location:
            class: Surfnet\StepupMiddleware\ApiBundle\Configuration\Service\RaLocationService
            arguments:
                - "@surfnet_stepup_middleware_api.repository.ra_location"

    surfnet_stepup_middleware_api.service.abstract_search:
        class: Surfnet\StepupMiddleware\ApiBundle\Identity\Service\AbstractSearchService
        abstract: true

    surfnet_stepup_middleware_api.service.second_factor:
        class: Surfnet\StepupMiddleware\ApiBundle\Identity\Service\SecondFactorService
        parent: surfnet_stepup_middleware_api.service.abstract_search
        arguments:
            - "@surfnet_stepup_middleware_api.repository.unverified_second_factor"
            - "@surfnet_stepup_middleware_api.repository.verified_second_factor"
            - "@surfnet_stepup_middleware_api.repository.vetted_second_factor"

    surfnet_stepup_middleware_api.service.institution_listing:
        class: Surfnet\StepupMiddleware\ApiBundle\Identity\Service\InstitutionListingService
        parent: surfnet_stepup_middleware_api.service.abstract_search
        arguments:
            - "@surfnet_stepup_middleware_api.repository.institution_listing"

    surfnet_stepup_middleware_api.service.ra_candidate:
        class: Surfnet\StepupMiddleware\ApiBundle\Identity\Service\RaCandidateService
        parent: surfnet_stepup_middleware_api.service.abstract_search
        arguments:
            - "@surfnet_stepup_middleware_api.repository.ra_candidate"

    surfnet_stepup_middleware_api.service.ra_second_factor:
        class: Surfnet\StepupMiddleware\ApiBundle\Identity\Service\RaSecondFactorService
        parent: surfnet_stepup_middleware_api.service.abstract_search
        arguments:
            - "@surfnet_stepup_middleware_api.repository.ra_second_factor"

    surfnet_stepup_middleware_api.service.identity:
        class: Surfnet\StepupMiddleware\ApiBundle\Identity\Service\IdentityService
        parent: surfnet_stepup_middleware_api.service.abstract_search
        arguments:
            - "@surfnet_stepup_middleware_api.repository.identity"
            - "@surfnet_stepup_middleware_api.repository.ra_listing"
            - "@surfnet_stepup_middleware_api.repository.sraa"

    surfnet_stepup_middleware_api.service.ra_listing:
        class: Surfnet\StepupMiddleware\ApiBundle\Identity\Service\RaListingService
        parent: surfnet_stepup_middleware_api.service.abstract_search
        arguments:
            - "@surfnet_stepup_middleware_api.repository.ra_listing"

    surfnet_stepup_middleware_api.service.sraa:
        class: Surfnet\StepupMiddleware\ApiBundle\Identity\Service\SraaService
        parent: surfnet_stepup_middleware_api.service.abstract_search
        arguments:
            - "@surfnet_stepup_middleware_api.repository.sraa"

    surfnet_stepup_middleware_api.service.audit_log:
        class: Surfnet\StepupMiddleware\ApiBundle\Identity\Service\AuditLogService
        parent: surfnet_stepup_middleware_api.service.abstract_search
        arguments:
            - "@surfnet_stepup_middleware_api.repository.audit_log"

    surfnet_stepup_middleware_api.service.whitelist_entry:
        class: Surfnet\StepupMiddleware\ApiBundle\Identity\Service\WhitelistService
        arguments:
            - "@surfnet_stepup_middleware_api.repository.whitelist_entry"

    # Param Converters
    surfnet_stepup_middleware_api.request.command_param_converter:
        class: Surfnet\StepupMiddleware\ApiBundle\Request\CommandParamConverter
        tags:
            - { name: request.param_converter, priority: -10, converter: surfnet_stepup_middleware_api.command }

    surfnet_stepup_middleware_api.request.metadata_param_converter:
        class: Surfnet\StepupMiddleware\ApiBundle\Request\MetadataParamConverter
        arguments:
            - "@validator"
        tags:
            - { name: request.param_converter, priority: -15, converter: surfnet_stepup_middleware_api.metadata }

    surfnet_stepup_middleware_api.request.institution_param_converter:
        class: Surfnet\StepupMiddleware\ApiBundle\Request\InstitutionParamConverter
        tags:
            - { name: request.param_converter, priority: -5, converter: surfnet_step_middleware.institution }

    surfnet_stepup_middleware_api.request.configuration_institution_param_converter:
        class: Surfnet\StepupMiddleware\ApiBundle\Request\ConfigurationInstitutionParamConverter
        tags:
            - name: request.param_converter
              priority: -4
              converter: surfnet_stepup_middleware_api.configuration_institution

    # Exception Listeners
    surfnet_stepup_middleware_api.listener.exception_listener:
            class: Surfnet\StepupMiddleware\ApiBundle\EventListener\ExceptionListener
            arguments:
                - "@logger"
            tags:
                - { name: kernel.event_listener, event: kernel.exception, method: onKernelException }

    # Security Entry Point
    surfnet_stepup_middleware_api.security.json_basic_auth_entry_point:
        class: Surfnet\StepupMiddleware\ApiBundle\Security\Http\EntryPoint\JsonBasicAuthenticationEntryPoint
        arguments:
            - ~ # HTTP Basic realm string, see extension
