surfnet_stepup_middleware_management:
    resource: "@SurfnetStepupMiddlewareManagementBundle/Resources/config/routing.yml"
    prefix:   /management

open_conext_monitor:
    resource: "@OpenConextMonitorBundle/src/Controller"
    type: attribute
    prefix: /

surfnet_stepup_middleware_api:
    resource: "@SurfnetStepupMiddlewareApiBundle/Resources/config/routing.yml"
