imports:
    - { resource: config.yml }

framework:
    router:
        resource: "%kernel.root_dir%/config/routing_dev.yml"
        strict_requirements: true
    profiler: { only_exceptions: false }

# Be careful not to remove the prod-signaler handler, which overwrites
# the prod-signaler handler defined in logging.yml. The handler defined
# in logging.yml disables bubbling which means that none of the handlers
# below are invoked. Since the current dev setup is incompatible with the
# prod setup defined in logging.yml, this means we won't see any logs in
# the infrastructure currently used (graylog). Overwriting the handler
# here resolves that and reinstates the dev logging setup.
#
# this configuration must be replaced to reflect production setup
# see https://www.pivotaltracker.com/story/show/96056010
#
monolog:
    handlers:
        prod-signaler:
            type: group
            members:
                - main_graylog
                - main_logfile
                - main_debuglog
        main_graylog:
            type:    buffer
            handler: graylog
            level:   NOTICE
        main_logfile:
            type:    stream
            handler: logfile
            level:   NOTICE
            path:    %kernel.logs_dir%/%kernel.environment%.log
        main_debuglog:
            type:    stream
            handler: logfile
            level:   DEBUG
            path:    "%kernel.logs_dir%/%kernel.environment%.debug.log"
        graylog:
            type:      gelf
            publisher: { hostname: %graylog_hostname% }
            formatter: surfnet_stepup.monolog.full_message_exception_gelf_message_formatter

swiftmailer:
    port: 1025

services:
    twig.extension.text: # Required by JMSTranslationBundle
        class: Twig_Extensions_Extension_Text
        tags: [{ name: twig.extension }]

jms_translation:
    locales: %locales%
    configs:
        default:
            dirs: [%kernel.root_dir%/../src, %kernel.root_dir%]
            output_dir: %kernel.root_dir%/Resources/translations
            ignored_domains: []
            excluded_names: ['*TestCase.php', '*Test.php']
            excluded_dirs: [cache, data, logs, Tests]
            extractors: []

nelmio_security:
    csp:
        report_only: true
