imports:
    - { resource: config_dev.yml }

framework:
    test: ~
    session:
        storage_id: session.storage.mock_file
    profiler:
        collect: false

web_profiler:
    toolbar: false
    intercept_redirects: false

swiftmailer:
    disable_delivery: true

doctrine:
    dbal:
        default_connection: middleware
        connections:
            middleware:
                driver: pdo_sqlite
                path: %kernel.cache_dir%/middleware.db
            gateway:
                driver: pdo_sqlite
                path: %kernel.cache_dir%/gateway.db
            deploy:
                driver: pdo_sqlite
                path: %kernel.cache_dir%/deploy.db

liip_functional_test:
    cache_sqlite_db: true
