imports:
    - { resource: config.yml }

framework:
    router:
        resource: "%kernel.root_dir%/config/routing_dev.yml"
        strict_requirements: true
    profiler: { only_exceptions: false }

# The monolog configuration below overwrites the in logging.yml that
# is normally used for production.
monolog:
    handlers:
        prod-signaler:
            type: fingers_crossed
            action_level: ERROR
            passthru_level: DEBUG # DEV setting: this means that all message of level DEBUG or higher are always logged
            #passthru_level: NOTICE # PROD setting this means that all message of level NOTICE or higher are always logged
            handler: main_syslog
            bubble: false # if we handle it, nothing else should
        main_syslog:
            type: syslog
            ident: stepup-middleware
            facility: user
            formatter: surfnet_stepup.monolog.json_formatter

swiftmailer:
    port: 1025

services:
    twig.extension.text: # Required by JMSTranslationBundle
        class: Twig_Extensions_Extension_Text
        tags: [{ name: twig.extension }]

jms_translation:
    locales: %locales%
    configs:
        default:
            dirs: [%kernel.root_dir%/../src, %kernel.root_dir%]
            output_dir: %kernel.root_dir%/Resources/translations
            ignored_domains: []
            excluded_names: ['*TestCase.php', '*Test.php']
            excluded_dirs: [cache, data, logs, Tests]
            extractors: []

nelmio_security:
    csp:
        report_only: true
