security:
    providers:
        in_memory:
            memory:
                users:
                    ss:
                        password: 'ss_password_test'
                        roles: 'ROLE_SS'
                    ra:
                        password: 'ra_password_test'
                        roles: 'ROLE_RA'
                    management:
                        password: 'management_password_test'
                        roles: 'ROLE_MANAGEMENT'

    encoders:
        Symfony\Component\Security\Core\User\User: plaintext
