services:
    surfnet_stepup_middleware_command_handling.command_handler.identity_command_handler:
        class: Surfnet\StepupMiddleware\CommandHandlingBundle\Identity\CommandHandler\IdentityCommandHandler
        arguments:
            - @surfnet_stepup.repository.identity
            - @identity.entity.configurable_settings
        tags: [{ name: command_bus.command_handler }]

    surfnet_stepup_middleware_command_handling.command_handler.registration_authority_command_handler:
        class: Surfnet\StepupMiddleware\CommandHandlingBundle\Identity\CommandHandler\RegistrationAuthorityCommandHandler
        arguments:
            - @surfnet_stepup.repository.identity
        tags: [{ name: command_bus.command_handler }]

    surfnet_stepup_middleware_command_handling.command_handler.configuration:
        class: Surfnet\StepupMiddleware\CommandHandlingBundle\Configuration\CommandHandler\ConfigurationCommandHandler
        arguments:
            - @surfnet_stepup.repository.configuration
        tags: [{ name: command_bus.command_handler }]

    surfnet_stepup_middleware_command_handling.command_handler.whitelist:
        class: Surfnet\StepupMiddleware\CommandHandlingBundle\Identity\CommandHandler\WhitelistCommandHandler
        arguments:
            - @surfnet_stepup.repository.whitelist
        tags: [{ name: command_bus.command_handler }]

