services:
    surfnet_stepup_middleware_command_handling.command_handler.identity_command_handler:
        class: Surfnet\StepupMiddleware\CommandHandlingBundle\Identity\CommandHandler\IdentityCommandHandler
        arguments:
            - @surfnet_stepup.repository.identity
            - @identity.entity.configurable_settings
        tags: [{ name: command_bus.command_handler }]

    surfnet_stepup_middleware_command_handling.command_handler.configuration:
        class: Surfnet\StepupMiddleware\CommandHandlingBundle\Configuration\CommandHandler\ConfigurationCommandHandler
        arguments:
            - @surfnet_stepup.repository.configuration
            - @surfnet_stepup_middleware_gateway.service.gateway_configuration
            - @surfnet_stepup_middleware_api.projector.raa
            - @surfnet_stepup_middleware_api.projector.sraa
            - @doctrine.dbal.middleware_connection
            - @doctrine.dbal.gateway_connection
        tags: [{ name: command_bus.command_handler }]

