services:
    surfnet_stepup_middleware_command_handling.command_handler.identity_command_handler:
        class: Surfnet\StepupMiddleware\CommandHandlingBundle\Identity\CommandHandler\IdentityCommandHandler
        arguments:
            - @surfnet_stepup.repository.identity
        tags: [{ name: command_bus.command_handler }]
