services:
    pipeline:
        alias: surfnet_stepup_middleware_command_handling.pipeline.transaction_aware_pipeline

    surfnet_stepup_middleware_command_handling.pipeline.transaction_aware_pipeline:
        class: Surfnet\StepupMiddleware\CommandHandlingBundle\Pipeline\TransactionAwarePipeline
        arguments:
            - @surfnet_stepup_middleware_command_handling.pipeline.staged_pipeline
            - @doctrine.dbal.middleware_connection

    surfnet_stepup_middleware_command_handling.pipeline.staged_pipeline:
        class: Surfnet\StepupMiddleware\CommandHandlingBundle\Pipeline\StagedPipeline
        arguments:
            - @logger

    surfnet_stepup_middleware_command_handling.pipeline.stage.validation:
        class: Surfnet\StepupMiddleware\CommandHandlingBundle\Pipeline\ValidationStage
        arguments: [ @validator ]
        tags: [{ name: pipeline.stage, priority: 2 }]

    surfnet_stepup_middleware_command_handling.pipeline.stage.dispatch:
        class: Surfnet\StepupMiddleware\CommandHandlingBundle\Pipeline\DispatchStage
        arguments:
            - @surfnet_stepup_middleware_command_handling.command_bus
        tags: [{ name: pipeline.stage, priority: 50 }]

    surfnet_stepup_middleware_command_handling.pipeline.stage.event_dispatching:
        class: Surfnet\StepupMiddleware\CommandHandlingBundle\Pipeline\EventDispatchingStage
        arguments:
            - @surfnet_stepup_middleware_command_handling.event_bus.buffered
            - @logger
        tags: [{ name: pipeline.stage, priority: 100 }]

    surfnet_stepup_middleware_command_handling.command_bus:
        class: Broadway\CommandHandling\SimpleCommandBus

    surfnet_stepup_middleware_command_handling.listener.invalid_command_exception_listener:
        class: Surfnet\StepupMiddleware\CommandHandlingBundle\EventListener\InvalidCommandExceptionListener
        tags: [{ name: kernel.event_subscriber }]
