services:
    pipeline:
        alias: surfnet_stepup_middleware_command_handling.pipeline.transaction_aware_pipeline

    surfnet_stepup_middleware_command_handling.pipeline.transaction_aware_pipeline:
        class: Surfnet\StepupMiddleware\CommandHandlingBundle\Pipeline\TransactionAwarePipeline
        arguments:
            - @logger
            - @surfnet_stepup_middleware_command_handling.pipeline.staged_pipeline
            - @doctrine.dbal.middleware_connection
            - @doctrine.dbal.gateway_connection

    surfnet_stepup_middleware_command_handling.pipeline.staged_pipeline:
        class: Surfnet\StepupMiddleware\CommandHandlingBundle\Pipeline\StagedPipeline
        arguments:
            - @logger

    surfnet_stepup_middleware_command_handling.pipeline.stage.authorizing:
        class: Surfnet\StepupMiddleware\CommandHandlingBundle\Pipeline\AuthorizingStage
        arguments:
            - @logger
            - @security.authorization_checker
        tags: [{ name: pipeline.stage, priority: 100 }]

    surfnet_stepup_middleware_command_handling.pipeline.stage.validation:
        class: Surfnet\StepupMiddleware\CommandHandlingBundle\Pipeline\ValidationStage
        arguments:
            - @logger
            - @validator
        tags: [{ name: pipeline.stage, priority: 75 }]

    surfnet_stepup_middleware_command_handling.pipeline.stage.dispatch:
        class: Surfnet\StepupMiddleware\CommandHandlingBundle\Pipeline\DispatchStage
        arguments:
            - @logger
            - @surfnet_stepup_middleware_command_handling.command_bus
        tags: [{ name: pipeline.stage, priority: 50 }]

    surfnet_stepup_middleware_command_handling.pipeline.stage.event_dispatching:
        class: Surfnet\StepupMiddleware\CommandHandlingBundle\Pipeline\EventDispatchingStage
        arguments:
            - @logger
            - @surfnet_stepup_middleware_command_handling.event_bus.buffered
        tags: [{ name: pipeline.stage, priority: 25 }]

    surfnet_stepup_middleware_command_handling.command_bus:
        class: Broadway\CommandHandling\SimpleCommandBus

    surfnet_stepup_middleware_command_handling.listener.invalid_command_exception_listener:
        class: Surfnet\StepupMiddleware\CommandHandlingBundle\EventListener\InvalidCommandExceptionListener
        tags:
            - { name: kernel.event_listener, event: kernel.exception, method: onKernelException, priority: 10 }
