services:
    surfnet_stepup_middleware_command_handling.processor.email:
        class: Surfnet\StepupMiddleware\CommandHandlingBundle\Identity\Processor\EmailProcessor
        arguments:
            - @surfnet_stepup_middleware_command_handling.service.second_factor_mail
            - @surfnet_stepup_middleware_api.service.ra
        tags: [{ name: event_bus.event_listener }]

    surfnet_stepup_middleware_command_handling.service.second_factor_mail:
        public: false
        class: Surfnet\StepupMiddleware\CommandHandlingBundle\Identity\Service\SecondFactorMailService
        arguments:
            - @mailer
            - @surfnet_stepup_middleware_command_handling.email_sender
            - @translator
            - @templating
            - '' # Verification URL set in bundle extension

    surfnet_stepup_middleware_command_handling.email_sender:
        public: false
        class: Surfnet\StepupMiddleware\CommandHandlingBundle\Value\Sender
        arguments:
            - ''
            - ''

    surfnet_stepup_middleware_command_handling.projector.email_templates:
        class: Surfnet\StepupMiddleware\CommandHandlingBundle\Configuration\Projector\EmailTemplatesProjector
        arguments:
            - @surfnet_stepup_middleware_command_handling.repository.email_template
        tags: [{ name: event_bus.event_listener }]

    surfnet_stepup_middleware_command_handling.repository.email_template:
        class: Surfnet\StepupMiddleware\CommandHandlingBundle\Configuration\Repository\EmailTemplateRepository
        factory_service: doctrine.orm.middleware_entity_manager
        factory_method: getRepository
        arguments: [ Surfnet\StepupMiddleware\CommandHandlingBundle\Configuration\Entity\EmailTemplate ]
