services:
    surfnet_stepup_middleware_command_handling.processor.email:
        class: Surfnet\StepupMiddleware\CommandHandlingBundle\Processor\EmailProcessor
        arguments:
            - "@surfnet_stepup_middleware_command_handling.service.second_factor_mail"
            - "@surfnet_stepup_middleware_api.service.ra_listing"
            - "@surfnet_stepup_middleware_api.service.institution_configuration_options"
            - "@surfnet_stepup_middleware_api.service.ra_location"
        tags: [{ name: event_bus.event_listener, disable_for_replay: true }]

    surfnet_stepup_middleware_command_handling.service.second_factor_mail:
        public: false
        class: Surfnet\StepupMiddleware\CommandHandlingBundle\Identity\Service\SecondFactorMailService
        arguments:
            - "@mailer"
            - "@surfnet_stepup_middleware_command_handling.email_sender"
            - "@translator"
            - "@templating"
            - "" # Verification URL set in bundle extension
            - "@surfnet_stepup_middleware_management.service.email_template"
            - "" # Fallback locale
            - "@logger"
            - true

    surfnet_stepup_middleware_command_handling.email_sender:
        public: false
        class: Surfnet\StepupMiddleware\CommandHandlingBundle\Value\Sender
        arguments:
            - "" # Name is set in bundle extension
            - "" # Email is set in bundle extension

    surfnet_stepup_middleware_command_handling.processor.institution_configuration:
        class: Surfnet\StepupMiddleware\CommandHandlingBundle\Configuration\Processor\InstitutionConfigurationProcessor
        arguments:
            - "@surfnet_stepup_middleware_api.repository.configured_institution"
            - "@service_container"
        tags: [{ name: event_bus.event_listener, disable_for_replay: true }]
