---

version: '3.7'

services:
  stepup-middleware:
    stdin_open: true
    image: ghcr.io/openconext/openconext-containers/openconext-php-test-stepup:latest
    volumes:
      - ../../:/var/www
    environment:
      APP_ENV: test
