services:
    middleware.event_replay.event_collection:
        class: Surfnet\StepupMiddleware\MiddlewareBundle\EventSourcing\EventCollection
        arguments:
            - "%registered_events%"

    middleware.event_replay.projector_collection:
        class: Surfnet\StepupMiddleware\MiddlewareBundle\EventSourcing\ProjectorCollection

    middleware.event_replay.transaction_aware_event_dispatcher:
        class: Surfnet\StepupMiddleware\MiddlewareBundle\Service\TransactionAwareEventDispatcher
        arguments:
            - "@surfnet_stepup_middleware_middleware.dbal_connection_helper"
            - "@middleware.event_replay.replaying_event_dispatcher"

    middleware.event_replay.replaying_event_dispatcher:
        class: Surfnet\StepupMiddleware\MiddlewareBundle\Service\ReplayingEventDispatcher

    middleware.event_replay.past_events_service:
        class: Surfnet\StepupMiddleware\MiddlewareBundle\Service\PastEventsService
        arguments:
            - "@middleware.event_replay.dbal_event_hydrator"

    middleware.event_replay.dbal_event_hydrator:
        public: false
        class: Surfnet\StepupMiddleware\MiddlewareBundle\EventSourcing\DBALEventHydrator
        arguments:
            - "@doctrine.dbal.middleware_connection"
            - "@surfnet_stepup.event_store.simple_serializer"
            - "@surfnet_stepup.event_store.simple_serializer"
            - 'event_stream'
            - 'event_stream_sensitive_data'

    middleware.event_replay.event_stream_replayer:
        public: true
        class: Surfnet\StepupMiddleware\MiddlewareBundle\Service\EventStreamReplayer
        arguments:
            - "@surfnet_stepup_middleware_command_handling.event_bus.buffered"
            - "@middleware.event_replay.dbal_event_hydrator"
            - "@surfnet_stepup_middleware_middleware.dbal_connection_helper"
