services:
    surfnet_stepup_middleware_middleware.dbal_connection_helper:
        class: Surfnet\StepupMiddleware\MiddlewareBundle\Service\DBALConnectionHelper
        arguments:
            -
                middleware: "@doctrine.dbal.middleware_connection"
                gateway: "@doctrine.dbal.gateway_connection"
