services:
  # Remove the public: true default once DI is implemented throughout the StepUp applications. See Pivotal #138225085
  _defaults:
    autowire: true
    autoconfigure: true
    public: false

  logger:
    alias: 'monolog.logger'
    public: true

  surfnet_stepup_middleware_middleware.dbal_connection_helper:
    class: Surfnet\StepupMiddleware\MiddlewareBundle\Service\DBALConnectionHelper
    arguments:
      - middleware: "@doctrine.dbal.middleware_connection"
        gateway: "@doctrine.dbal.gateway_connection"
        deploy: "@doctrine.dbal.deploy_connection"

  surfnet_stepup_middleware_middleware.institution_configuration_provider:
    class: Surfnet\StepupMiddleware\MiddlewareBundle\Migrations\InstitutionConfiguration\InstitutionConfigurationProvider
    arguments:
      - "@surfnet_stepup_middleware_api.service.configured_institutions"
      - "@surfnet_stepup_middleware_api.service.institution_configuration_options"
      - "@surfnet_stepup_middleware_api.service.ra_location"

  surfnet_stepup_middleware_middleware.verfied_second_factor_reminder:
    class: Surfnet\StepupMiddleware\MiddlewareBundle\Service\VerifiedSecondFactorReminderService
    arguments:
      - "@surfnet_stepup_middleware_api.repository.verified_second_factor"
      - "@surfnet_stepup_middleware_api.repository.identity"
      - "@surfnet_stepup_middleware_middleware.verfied_second_factor_reminder_mailer"
      - "@logger"

  surfnet_stepup_middleware_middleware.verfied_second_factor_reminder_mailer:
    class: Surfnet\StepupMiddleware\MiddlewareBundle\Service\VerifiedSecondFactorReminderMailService
    arguments:
      - "@mailer.mailer"
      - "@surfnet_stepup_middleware_command_handling.email_sender"
      - "@translator"
      - "@surfnet_stepup_middleware_management.service.email_template"
      - "@surfnet_stepup_middleware_api.service.institution_configuration_options"
      - "@surfnet_stepup_middleware_api.service.ra_listing"
      - "@surfnet_stepup_middleware_api.service.ra_location"
      - "" # Fallback locale

  surfnet_stepup_middleware_middleware.second_factor_display_name_resolver:
    public: false
    class: Surfnet\StepupMiddleware\MiddlewareBundle\Service\SecondFactorDisplayNameResolverService
    arguments: [ '%second_factors_display_name%' ]
