services:
    surfnet_stepup_middleware_middleware.dbal_connection_helper:
        class: Surfnet\StepupMiddleware\MiddlewareBundle\Service\DBALConnectionHelper
        arguments:
            -
                middleware: "@doctrine.dbal.middleware_connection"
                gateway: "@doctrine.dbal.gateway_connection"

    surfnet_stepup_middleware_middleware.institution_configuration_provider:
        class: Surfnet\StepupMiddleware\MiddlewareBundle\Migrations\InstitutionConfiguration\InstitutionConfigurationProvider
        arguments:
            - "@surfnet_stepup_middleware_api.service.configured_institutions"
            - "@surfnet_stepup_middleware_api.service.institution_configuration_options"
            - "@surfnet_stepup_middleware_api.service.ra_location"
