services:
    surfnet_stepup_middleware_middleware.command.bootstrap_identity_with_yubikey_second_factor:
        class: Surfnet\StepupMiddleware\MiddlewareBundle\Console\Command\BootstrapIdentityWithYubikeySecondFactorCommand
        arguments:
            - @pipeline
            - @surfnet_stepup_middleware_command_handling.event_bus.buffered
            - @doctrine.dbal.middleware_connection
            - @doctrine.dbal.gateway_connection
        tags:
            - { name: console.command }
