#!/usr/bin/env bash

#cd $(dirname $0)/../../
#
## https://github.com/sebastianbergmann/phpcpd
#./vendor/bin/phpcpd --exclude src/*/Tests/* src

# PHPCS is currently disabled due to Xdebug throwing a fatal error.
echo "Skipping PHPCPD due to Xdebug fatal error"
exit 0
