#!/usr/bin/env bash

# Exit the script when any of the statements has a non-true return value
set -e

cd $(dirname $0)/../../

# PHPUnit Bridge should always be used in Symfony applications. (https://symfony.com/doc/current/components/phpunit_bridge.html)
# This will create a phpunit executable in /bin/ instead of /vendor/bin/
./vendor/bin/phpunit --configuration=ci/qa/phpunit.xml --stop-on-error $@
./vendor/bin/phpunit --configuration=ci/qa/phpunit.xml --testsuite=database
