management_configuration_update:
  path: /configuration
  defaults: { _controller: Surfnet\StepupMiddleware\ManagementBundle\Controller\ConfigurationController::update }
  methods: [ POST ]
  condition: "request.headers.get('Content-Type') == 'application/json' && request.headers.get('Accept') matches '/^application\\\\/json($|[;,])/'"

management_institution_configuration_show:
  path: /institution-configuration
  defaults: { _controller: Surfnet\StepupMiddleware\ManagementBundle\Controller\InstitutionConfigurationController::show }
  methods: [ GET ]
  condition: "request.headers.get('Content-Type') == 'application/json' && request.headers.get('Accept') matches '/^application\\\\/json($|[;,])/'"

management_institution_configuration_reconfigure:
  path: /institution-configuration
  defaults: { _controller: Surfnet\StepupMiddleware\ManagementBundle\Controller\InstitutionConfigurationController::reconfigure }
  methods: [ POST ]
  condition: "request.headers.get('Content-Type') == 'application/json' && request.headers.get('Accept') matches '/^application\\\\/json($|[;,])/'"

management_whitelist_add:
  path: /whitelist/add
  defaults: { _controller: Surfnet\StepupMiddleware\ManagementBundle\Controller\WhitelistController::addToWhitelist }
  methods: [ POST ]
  condition: "request.headers.get('Content-Type') == 'application/json' && request.headers.get('Accept') matches '/^application\\\\/json($|[;,])/'"

management_whitelist_replace:
  path: /whitelist/replace
  defaults: { _controller: Surfnet\StepupMiddleware\ManagementBundle\Controller\WhitelistController::replaceWhitelist }
  methods: [ POST ]
  condition: "request.headers.get('Content-Type') == 'application/json' && request.headers.get('Accept') matches '/^application\\\\/json($|[;,])/'"

management_whitelist_remove:
  path: /whitelist/remove
  defaults: { _controller: Surfnet\StepupMiddleware\ManagementBundle\Controller\WhitelistController::removeFromWhitelist }
  methods: [ POST ]
  condition: "request.headers.get('Content-Type') == 'application/json' && request.headers.get('Accept') matches '/^application\\\\/json($|[;,])/'"

management_whitelist_show:
  path: /whitelist
  defaults: { _controller: Surfnet\StepupMiddleware\ManagementBundle\Controller\WhitelistController::showWhitelist }
  methods: [ GET ]
  condition: "request.headers.get('Accept') matches '/^application\\\\/json($|[;,])/'"

management_forget_identity:
  path: /forget-identity
  defaults: { _controller: Surfnet\StepupMiddleware\ManagementBundle\Controller\RightToBeForgottenController::forgetIdentity }
  methods: [ POST ]
  condition: "request.headers.get('Content-Type') == 'application/json' && request.headers.get('Accept') matches '/^application\\\\/json($|[;,])/'"

