doctrine:
    dbal:
        default_connection: middleware
        connections:
            middleware:
                dbname: middleware_test
                host: localhost
                password: password
                user: root
            gateway:
                dbname: gateway_test
                host: localhost
                password: password
                user: root
            deploy:
                dbname: middleware_test
