doctrine:
    dbal:
        default_connection: middleware
        connections:
            middleware:
                dbname: "%database_middleware_name%_test"
                host: localhost
                password: password
                user: root
            gateway:
                dbname: "%database_gateway_name%_test"
                host: localhost
                password: password
                user: root
            deploy:
                dbname: "%database_middleware_name%_test"
